sources:
  - name: fx
    config:
      enabled: true
    tables:
      - name: fx_sgd
  - name: invm
    config:
      enabled: true
    tables:
      - name: hkdusd_invm
      - name: sgd_cdp_invm
      - name: sgd_fundingsoc
      - name: sgd_invm
      - name: usd_invm
  - name: bank
    config:
      enabled: true
    tables:
      - name: sg_sgd_uobcc
      - name: sg_sgd_uob
      - name: hk_hkd_hangseng
      - name: fr_eur_hsbcfr
      - name: sg_eur_revolut_v2
      - name: sg_sgd_adjustments
      - name: sg_other_revolut_v2
      - name: sg_sgd_revolut_v2
      - name: de_eur_n26
      - name: sg_sgd_dbs
      - name: sg_sgd_hsbccc
      - name: sg_sgd_citicc
      - name: sg_eur_revolut_v1
      - name: sg_sgd_revolut_v1
      - name: sg_sgd_scbcc
      - name: sg_sgd_ocbc_v1
